- eva-server/pom.xml
- eva-server/src/main/resources/eva.properties
- eva-server/src/main/webapp/WEB-INF/web.xml
- eva-server/src/main/webapp/webservices/api/index.html
Swagger and general properties can now be configured using Maven profiles. The files affected by these are:
* web.xml: Swagger base path (using app context root) and EVAPRO data source
* eva.properties: Connection details and EVAPRO data source
* webapp/.../index.html: Dynamic URL in the Swagger JSON textbox, based on host where the WAR is deployed. Maven profiles don't seem to work, even after adding the folder to the resources section in the POM.
A sample settings.xml file will be shared internally.
> Customisable configuration EVA-388

- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/GeneWSServer.java
Added POST method to the genes/variants endpoint, and support for querying multiple gene IDs using GET and POST methods.
> Query multiple genes in genes/variants endpoint - EVA-418

- eva-lib/src/main/java/uk/ac/ebi/variation/eva/lib/datastore/DBAdaptorConnector.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/Application.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ApplicationConfiguration.java
- eva-server/src/main/resources/eva.properties
- eva-server/src/test/java/uk/ac/ebi/variation/eva/lib/datastore/DBAdaptorConnectorTest.java
- eva-server/src/test/resources/eva.properties
also add tests for DBAdaptorConnector
test methods:
- correct autowiring for MultiMongoDbFactory
- "read preference" option properly loaded from properties
> EVA-451 allow to specify the read preference for mongo

- eva-lib/pom.xml
- eva-server/pom.xml
- pom.xml
> EVA-462 Version bumped to 1.3

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepository.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryCustom.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryImpl.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/Utils.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerTest.java
- Regression Test for RegionWSServer
- RegionWSServer now uses VariantEntityRepository to query the MongoDB database
> EVA-366 RegionWSServer using VariantEntityRepository

- eva-lib/pom.xml
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/MongoConfiguration.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/utils/DBAdaptorConnector.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
- eva-server/pom.xml
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerTest.java
- pom.xml
- Added exclusions for mongo driver to dependencies
- Mongo 3 dependency from Spring Boot dependency
- Initialised credentials list, cannot be null in v3 of the driver- was preventing successful deployment
> EVA-612 Moved Mongo driver version to version 3

- .travis.yml
- install-dependencies.sh
First approach to continuous integration for this project, just checking that it compiles successfully in a clean environment. In the future we will be able to make it run the tests too.
> EVA-600 Travis checks "compile" Maven target only

- eva-lib/pom.xml
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepository.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryCustom.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryImpl.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/RepositoryConfiguration.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/Utils.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/UtilsTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerTest.java
- Added option to webservices to specify fields to exclude from being returned
- Modified repository methods to exclude the specified fields from being returned by Mongo
> EVA-612 Option to exclude fields from documents returned

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/metadata/ArchiveEvaproDBAdaptor.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/utils/EvaproDbUtils.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/configuration/MongoRepositoryTestConfiguration.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryImplTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/Application.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/JpaRepositoryConfiguration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/MongoEvaLibConfiguration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/Swagger2Configuration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/FeatureWSServer.java
Moved and refactored repository configuration.
> EVA-637 Improvement of EVA-WS Spring configuration

- install-dependencies.sh
- pom.xml
the changes are the update to opencga 0.5.3 in the pom.xml, and the update to ebivariation/opencga/hotfix/0.5 (0.5.3 and beyond) and ebivariation/biodata/hotfix/0.4 (0.4.6 and beyond) in the travis script.
> bring into develop the last version updates from master

- .gitignore
- eva-lib/pom.xml
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/DgvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/EvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/File.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/Project.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/Taxonomy.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/metadata/StudyDgvaDBAdaptor.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/ArchiveDgvaDBAdaptorTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/ArchiveEvaproDBAdaptorTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/DgvaStudyTestData.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/EvaStudyBrowserTestData.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/FileTestData.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/MetadataTestConfiguration.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/MetadataTestData.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/StudyDgvaDBAdaptorTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/StudyEvaproDBAdaptorTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/VariantSourceEvaProDBAdaptorTest.java
- eva-lib/src/test/resources/data.sql
- eva-lib/src/test/resources/schema.sql
- pom.xml
Added Evapro y Dgva adaptors tests
> EVA-588 Evapro db tests

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconResponse.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantCallSetWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantSetWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantWSServerTest.java
Use of SpringBootTests and Mockito to test the GA4GH webservices.
Requires latest changes to hotfix/0.4 branch of EBIvariation/biodata, including merging of the PR: https://github.com/EBIvariation/biodata/pull/6.
> EVA-681 GA4GH web services using Spring - Testing

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryImpl.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
Changed method for counting variants within given ranges (and filters) to using an aggregate.
> EVA-737 Improve correctness (and performance?) of method for counting variants found

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepository.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerTest.java
- New VariantEntityRepository queries for finding by coords and study
- Use of these new methods in VariantWSServer for checking variant existence
> EVA-757 Migrate variant/exists to using Spring repository

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerIntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerIntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerIntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/WSTestHelpers.java
Map API exclude name to model names in GeneWSServer
> EVA-877 Variant browser search by gene query fails

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entities/DgvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entities/EvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/metadata/StudyEvaproDBAdaptor.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/models/VariantStudy.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ArchiveWSServerTest.java
Assembly accession added to `VariantStudy` model, so it is listed in corresponding endpoints.
> EVA-863 Bugfix for genome assembly missing from study pages

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java
Improve error codes returned in variant search endpoints #78
> Improve error codes returned in variant search endpoints (issue #78)

- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantWSServerTest.java
- pom.xml
This is needed to return the `mainId` when calling the web services
> EVA-981 Upgrade to variation commons 0.7-SNAPSHOT

- .gitlab-ci.yml
Start ci on an environment only when the corresponding branch is updated
> Test gitlab CI pipeline

- .gitlab-ci.yml
- .gitlab.settings.xml
> add production profile pointing to development and production ci steps

- README.md
I took the oportunity to update the old instructions.
> EVA-1447 Update README.md to test GitHub webhooks

- pom.xml
tested locally: compiles, deploys and works fine.
> EVA-1404 Address Github security vulnerability notifications for various repositories

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/beaconv2/BeaconServiceV2.java
aim for this PR:
- Support studies with multiple files for Beacon
> Improvebeacon

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/beaconv2/BeaconImpl.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/beaconv2/BeaconServiceV2.java
This PR replaces some of the placeholder comments of secondary attribute with their actual values.
> Hard-coded beacon strings

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/IdentifierWSServerV2.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/IdentifierWSServerV2IntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/IdentifierWSServerV2Test.java
The purpose of this PR is to add hateoas feature to identifierv2 endpoint.
> Hateoas to identifier v2

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServerV2.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerV2IntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerV2Test.java
The purpose of this PR is to add pagination feature to RegionWSServerV2 endpoint
> Add pagination to region server v2

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2IntegrationTest.java
The purpose of this PR is to add additional search parameters to GeneWSServerV2
> Improve GeneWSServerV2

- .gitlab-ci.yml
Set the development environment to use the production_processing profile to give it access to the prod database
> Set wwwdev to use the production_processing profile

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entities/FileSample.java
> EVA-3883: Fix embedded ID annotations
