EBIvariation/eva-ws

- eva-lib/src/main/java/uk/ac/ebi/variation/eva/lib/storage/metadata/VariantSourceEvaproDBAdaptor.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/EvaWSServer.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/GeneWSServer.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/RegionWSServer.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/StudyWSServer.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/VariantWSServer.java
- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/ga4gh/GA4GHVariantWSServer.java
The conversion was properly done in the web services that return Variant objects, but not in those that return VariantSource objects.
> Convert PRJEB/ERZ IDs also when returning VariantSource objects

- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/GeneWSServer.java
Bugfix for the cases when the web service that retrieves the variants in a gene couldn't process an argument like `maf=>0.3`, but worked with `maf=0.3` (exact search) and without that argument at all.
The reason for this was that the old WS interface used both "maf" and "mafOp" as arguments, whereas the next versions of OpenCGA only required "maf", including the operator in that argument.
> Gene web service supporting interval MAF arguments

- eva-server/src/main/java/uk/ac/ebi/variation/eva/server/ws/VariantWSServer.java
Requests with symbolic ALT IDs such as `7:83532609:T:<INS:ME:ALU>` were failing due to an incorrect handling of the colon separator, treated the same way in and out of the angle brackets.
> Fixed search of symbolic ALT IDs in variants/info web service

- pom.xml
Spring Boot favours Logback as logging library, that can be easily integrated with SLF4J. It was not possible to deploy the WAR file due to an extra SLF4J declaration.
> EVA-440 Removed conflicting logging dependencies

- README.md
- eva-server/pom.xml
- eva-server/src/main/java/uk/ac/ebi/eva/server/AuthorizationConfiguration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/Profiles.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/security/CORSResponseFilter.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/security/authorization/Oauth2Configuration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/security/authorization/UnsecureConfiguration.java
- eva-server/src/main/resources/application.properties
- eva-server/src/main/webapp/WEB-INF/web.xml
~~Added new property~~
~~`eva.server.security.enabled`~~
After enabled it can be used to check a Bearer oauth2 credential against a server using the standard configuration properties from Spring-oauth2.
`security.oauth2.resource.user-info-uri`
> EVA-471 Securing REST API

- .travis.yml
- eva-lib/pom.xml
- eva-server/pom.xml
- install-dependencies.sh
- pom.xml
Requires code from https://github.com/EBIvariation/opencga/pull/1 and the Travis script to be modified to clone the latest dependencies versions.
* OpenCGA upgraded to 0.5.3
* Project upgraded to 1.3.1
> Version upgrades

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entity/File.java
The ';' causes an exception (parameter [filenames] not found)
> Fixed bug in named query

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepository.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryCustom.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryImpl.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantEntityRepositoryTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantSourceEntityRepositoryTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/VariantStudySummaryRepositoryTest.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerTest.java
Requires https://github.com/EBIvariation/variation-commons/pull/31/files variation commons PR merging.
To fix issue with samplesData not being populated in variant entities returned from repository (due to sample name information not being present in variant collection.
- Requires [updated DBObjectToSamplesConverter in variation commons](https://github.com/EBIvariation/variation-commons/pull/31), which adds sample data to variant source entries in the variant entity being converted, but uses the samples position/index in the file as the key (rather than the sample name), for the default genotype string it uses just one map entry ("def" -> defaultGtString).
- VariantEntityRepositoryImpl receives variant entities with samplesData in this format.
- VariantEntityRepositoryImpl queries the …
> EVA-742 Samples data not displayed

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/MongoConfiguration.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/repository/AnnotationMetadataRepository.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/repository/AnnotationMetadataRepositoryTest.java
- eva-lib/src/test/resources/eva.properties
- eva-lib/src/test/resources/test-data/annotation_metadata.json
- eva-server/pom.xml
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/AnnotationMetadataWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/AnnotationMetadataWSServerTest.java
- pom.xml
- Repository for AnnotationMetadata, and tests
- Webservice for AnnotationMetadata, using above repository 
- https://github.com/EBIvariation/variation-commons/pull/29 Needs to be merged first, because this PR relies upon it, which is why the tests are failing for this PR
> EVA-349 Web service for VEP and Ensembl cache used

- eva-lib/pom.xml
- eva-server/pom.xml
- eva-server/src/main/resources/application.properties
- eva-server/src/main/resources/eva.properties
- pom.xml
* Using variation-commons version 0.2.1 including bugfix from [variation-commons#34](https://github.com/EBIvariation/variation-commons/pull/34), which needs to be pushed to Artifactory in order for this build to pass
* Version bumped to 1.4 final
* Populates correctly the HGVS
* OpenCGA dependency managed in variation-commons for consistency across all EVA repositories
**Note:** These changes will need to be ported to branch 1.5-develop.
> EVA-770 Display populated HGVS field

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/models/ga4gh/GAVariantFactory.java
- eva-server/pom.xml
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/JacksonConfiguration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerIntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/RegionWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHBeaconWSServerTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/GA4GHVariantWSServerTest.java
- eva-server/src/test/resources/test-data/annotation_metadata.json
- eva-server/src/test/resources/test-data/annotations.json
- pom.xml
- Use of new VariantWithSamplesAndAnnotation model
- Allows filtering by vep and vep cache version
- Requires PR in variation-commons to be deployed: https://github.com/EBIvariation/variation-commons/pull/39
> EVA-797 Implement filter at API level

- eva-lib/pom.xml
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/json/ConsequenceTypeMixin.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/json/SoTermsDeserializer.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/json/SoTermsSerializer.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/utils/ConsequenceTypeMappings.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/utils/SOTermNotAvailableException.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/json/SoTermsDeserializerTest.java
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/json/SoTermsSerializerTest.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/JacksonConfiguration.java
this is the structure for consequence types this PR achieves (taken from localhost swagger):
"annotation": {
"chromosome": "20",
"start": 60343,
"end": 60343,
"vepVersion": "78",
"vepCacheVersion": "78",
"consequenceTypes": [
{
"soTerms": [
{
"soName": "intergenic_variant",
"soAccession": "SO:0001628"
}
]
}
]
}
> EVA-820 SO name is not displayed for consequence types

- dgva-server/pom.xml
- dgva-server/src/test/java/uk/ac/ebi/dgva/server/ws/ArchiveWSServerTest.java
- eva-lib/pom.xml
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/eva_utils/EvaproDbUtils.java
- eva-server/pom.xml
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ArchiveWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServer.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/StudyWSServer.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ArchiveWSServerTest.java
- pom.xml
Updated poms and imports to correspond with new variation-commons submodule structure.
The PR https://github.com/EBIvariation/variation-commons/pull/42 needs merging and deploying before this will build correctly.
> EVA-835 Prevent unnecessary DBMS driver dependencies from being exported

- eva-server/pom.xml
- pom.xml
Use 0.4.1 version of variation-commons. Requires the PR https://github.com/EBIvariation/variation-commons/pull/43 to be merged and deployed.
> EVA-837 Support databases with no VEP annotation

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/EvaWSServer.java
The existing implementation of `setQueryResponse` wrapped anything that was returned in a collection. When the returned value is a collection itself this causes excessive nesting.
> EVA-879 Do not wrap collections in another collection when building response

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/json/VariantStudyMixin.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ArchiveWSServerTest.java
Our default visibility policy is defined in a way that attributes are serialized, but getters are not. This is usually fine, but variant studies have a getter for user-friendly display of their type. This PR fixes the issue that prevented them from being returned in the response.
This issue does not affect the new DGVa web services yet, but when they are configured in the same way as the EVA ones it would.
> DGVA-64 Study type name should not be ignored

- eva-lib/pom.xml
- eva-server/pom.xml
- pom.xml
By using variation-commons 0.4.3 (requires https://github.com/EBIvariation/variation-commons/pull/48), population statistics are no longer re-calculated after reading variants from the database.
> EVA-917 Bugfix for allele frequencies not correctly mapped from Mongo to JSON

- dgva-server/src/test/java/uk/ac/ebi/dgva/server/ws/ArchiveWSServerTest.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entities/DgvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/entities/EvaStudyBrowser.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/models/VariantStudy.java
- eva-lib/src/main/resources/study_browser.sql
- eva-lib/src/test/java/uk/ac/ebi/eva/lib/metadata/eva/EvaStudyBrowserTestData.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ArchiveWSServerTest.java
Add the attribute `browsable` to VariantStudy and EvaStudyBrowser, so that the endpoint meta/studies/all returns studies with a flag telling if it is browsable or not. All browsable studies have at least one file in the table `browsable_file`.
evapro needs to update the materialized view `study_browser` to add 
```
, COALESCE(browsable_table.browsable, false) AS browsable
```
and 
```
LEFT JOIN ( SELECT browsable_file.project_accession,
true AS browsable
FROM browsable_file
GROUP BY browsable_file.project_accession) browsable_table(project_accession_browsable, browsable) 
ON browsable_table.project_accession_browsable::text = project.project_accession::text
```
the full command for creating the materialized view is now in eva-lib/src/main/resources/study_browser.sql.
> EVA-812 Links to submitted and curated FTP in study view page

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/dgva_utils/DgvaDBUtils.java
- eva-lib/src/main/java/uk/ac/ebi/eva/lib/extension/GenericSpecifications.java
DGVa study browser filter by species fixed for comma-separated lists of them. For instance, queries to "chimpanzee" didn't return any results before because this species was always part of studies where multiple primate species were sequenced.
> DGVA-91 DGVA study browser filters

- .gitlab-ci.yml
[An issue on JDK8-u181](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925) makes the GitLab CI build fail because the `ForkedBooter` class can't be found. This bugfix is based on the suggestion made in [this StackOverflow message](https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class/53085816#53085816).
In addition to that, after adding the commit number to the built WAR file, it was no longer copying the artifact for deployment. By using a wildcard it recognizes the new naming style.
> EVA-1119 Fix GitLab CI build

- .gitlab-ci.yml
Remove `EVA1288` from the URL
The deployment to tomcat still does not include the version
> EVA-1119 Fix URL Gitlab CI build

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/ga4gh/beaconv2/BeaconServiceV2.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/ga4gh/beaconv2/GA4GHBeaconWSServerV2Test.java
The purpose of this PR is to add checks so that querying of imprecise queries is only allowed when all of startMin,startMax,endMin and endMax are present.
Also, in the case where `includeDatasetResponses` is `None`, an optimization is done by not calling `findByRegionAndOtherBeaconFilters`
> bug fix and optimization for beaconquery

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServerV2.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerV2IntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/VariantWSServerV2Test.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/WSTestHelpers.java
The purpose of this PR is to remove the usage of  `QueryResponse` in VariantWSServerV2 and associated tests.
> Improve variant ws server v2

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2.java
- eva-server/src/main/resources/application.properties
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2IntegrationTest.java
- eva-server/src/test/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2Test.java
- eva-server/src/test/resources/test-data/features.json
The purpose of this PR is to add an endpoint "/v2/genes/{geneIds}" which retrieves a list of `FeatureCoordinates` for the given geneIds.
> Gene ws server v2

- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/GeneWSServerV2.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/RegionWSServerV2.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServerV2.java
The purpose of this PR is to add parameter description for parameters in the V2 APIs
> Added description for  parameters

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/utils/ConsequenceTypeMappings.java
After fix, most severe consequence type appears correctly: https://wwwdev.ebi.ac.uk/eva/?Variant-Browser&species=ecaballus_20&selectFilter=region&region=1%3A260000-270000
> EVA-1104 - Take out mappings for 2KB upstream and downstream variants per VEP

- eva-lib/src/main/java/uk/ac/ebi/eva/lib/MongoConfiguration.java
- eva-server/src/main/java/uk/ac/ebi/eva/server/configuration/MongoEvaLibConfiguration.java
- eva-server/src/main/resources/application.properties
- eva-server/src/test/java/uk/ac/ebi/eva/server/configuration/MongoRepositoryTestConfiguration.java
When attempting to deploy eva-ws after the [Spring 2 upgrade PR](https://github.com/EBIvariation/eva-ws/pull/137), there were some issues encountered:
- Spring Boot 2 requires an explicit MongoTemplate bean (fixed in this PR)
- Spring Boot 2 also requires an explicit authentication mechanism to be specified if there is a username and password supplied (fixed in this PR)
- HTTP 500 error thrown when attempting to test the variant endpoint. This is due to the binary type in the **files.attrs.src** MongoDB attribute (Variant source) not being directly castable to "byte[]" with the Spring Boot 2 MongoDB Java Driver. This is addressed in [another PR](https://github.com/EBIvariation/variation-commons/pull/94)
> EVA-1902 - Fix Spring Boot 2 application deployment issues

- .gitlab-ci.yml
Based on Nitin's comment [here](https://docs.google.com/document/d/1kisKFmtCg9rCGFOlb7gqf4j1GgHIGBcmhSVaRJGQPvw/edit?disco=AAAAaAzdBTA), use production_processing profile.
> EVA-2823 - Use production_processing profile instead of evapro-staging
